dreikanter/feeder

- app/normalizers/dilbert_normalizer.rb
- test/data/feed_dilbert.xml
- test/normalizers/dilbert_normalizer_test.rb
Hi @dreikanter 
This PR is linked to the issue [#211](https://github.com/dreikanter/feeder/issues/211).
The idea is to make changes to add titles to the Dilbert feed.
I hope it's all good.
Tks.
Leandro.
> Add titles to the Dilbert feed

- app/normalizers/rework_normalizer.rb
- config/feeds.yml
- test/feeds/rework_test.rb
- test/fixtures/files/entities/rework.json
- test/fixtures/files/feeds/rework.xml
HB: https://app.honeybadger.io/projects/65419/faults/58859438
> Fix Rework summary

- test/fixtures/files/entities/rework.json
> Fix test data

- app/services/error_dumper.rb
Updates:
- Extract file name and line number from backtrace when error `location` is not available.
> Improve error context extraction

- README.md
- config/database.yml
- config/environments/development.rb
- docker-compose.yml
- docker/DockerFile
- docker/start-service.sh
Issue link : [ISSUE-250](https://github.com/dreikanter/feeder/issues/250)
- docker-compose.yml which contains configuration of feeder service app and postgres db
- DockerFile which contains the steps to build feeder service docker image
- start-service script to enable provisions to start and stop feeder service application
- config/database.yml to get database url from environment variable
- config/environments/development.rb to allow any private ip from hitting the application 
- Reason being, when you start the webpack service inside the docker container, it is getting assigned to a random private ip and not only in 192.168.0.0 range.
- The change is done _only in development environment_ and not in production / test environment, hence it won't affect the application when it is run in …
> [ISSUE-250]: docker setup for feeder app

- .github/workflows/workflow.yml
- .rubocop.yml
> Cache gems and NPM packages

- config/feeds.yml
> Add lizandmollie feed

- config/feeds.yml
Attempting to fix Reddit API limit error.
https://app.honeybadger.io/projects/65419/faults/81437832
> Increase Reddit poll period

- app/normalizers/xkcd_normalizer.rb
- test/feeds/xkcd_test.rb
- test/fixtures/files/feeds/xkcd/entity.json
- test/fixtures/files/feeds/xkcd/post.html
- test/normalizers/xkcd_normalizer_test.rb
> Extract XKCD image URL from OpenGraph meta tag

- app/normalizers/xkcd_normalizer.rb
- test/feeds/xkcd_test.rb
- test/fixtures/files/feeds/xkcd/entity.json
- test/fixtures/files/feeds/xkcd/post.html
- test/normalizers/xkcd_normalizer_test.rb
* Extract XKCD image URL from OpenGraph meta tag
* Rubocop
* Update feed test
> Release: Extract XKCD image URL from OpenGraph meta tag (#331)

- app/normalizers/monkeyuser_normalizer.rb
- test/normalizers/monkeyuser_normalizer_test.rb
* Update gems
* Add image alt text to the monkeyuser comments
* Remove bundler version constraing from Gemfile.lock
* Somplify feed entry parsing
> Add image alt text to the monkeyuser comments (#343)

- app/normalizers/zippy_normalizer.rb
- config/feeds.yml
- test/feeds/zippy_test.rb
- test/fixtures/files/feeds/zippy/entity.json
- test/fixtures/files/feeds/zippy/feed.xml
https://github.com/dreikanter/feeder/issues/357
> Add `zippy` feed

- Gemfile.lock
- config/environments/production.rb
- config/feeds.yml
See https://github.com/dreikanter/feeder/issues/369
> Add `yesbut` feed

- app/normalizers/yesbut_normalizer.rb
- config/feeds.yml
> Introduce `yesbut` normalizer to customize post formatting

- config/feeds.yml
References:
- Request: https://freefeed.net/feeder-inbox/a0c7656f-f2a3-4570-bccf-8432b6e6afe2
- https://www.youtube.com/@hubermanlab
- https://www.youtube.com/@veritasium
> Add veritasium and hubermanlab feeds

- bin/release_master
- config/feeds.yml
> Update Reddit feed settings

- Dockerfile
- app/controllers/dashboards_controller.rb
- app/helpers/formatting_helper.rb
- app/models/feed.rb
- app/views/dashboards/show.html.erb
- app/views/layouts/application.html.erb
- Fix the tooltip displaying feed error counters.
- Update feeds order.
- Display import stats.
- Order feeds by state.
- Display feeds state instead of the status.
> Fix errors count presentation and display import stats

- README.md
- app/normalizers/nitter_normalizer.rb
- test/normalizers/nitter_normalizer_test.rb
Twitter previews are redundant. This patch adds `!` before Tweet permalink.
> Disable Twitter preview

- Gemfile
- Gemfile.lock
Preparing to Ruby 3 transition.
> Explicit dependency definition for `rss` gem

- config/feeds.yml
Adjust refresh intervals and disable inactive feeds.
> Refresh feeds configuration

- app/helpers/feeds_table_helper.rb
- app/models/feed.rb
- app/services/feeds.rb
- db/migrate/20230613121056_change_feed_state_default.rb
- db/schema.rb
- spec/service/feeds_spec.rb
Changes:
- Introduce `pristine` and `paused` states.
- Relace `removed` with `disabled`.
- Relace `disabled` with `paused`.
- Pause and unpause transitions.
> Update feed state transitions

- app/services/feed_sanitizer.rb
- db/migrate/20230615035946_add_disabling_reason_to_feeds.rb
- db/schema.rb
- spec/fixtures/files/sample_feeds.yml
- spec/service/feeds_configuration_spec.rb
- spec/services/feed_sanitizer_spec.rb
Changes:
- Add feed description, source site URL and deactivation reason to the Feed model.
- Update new fields from the configuration.
References:
- https://github.com/dreikanter/feeder/issues/394
> Add more columns to the feeds table

- app/models/feed.rb
- spec/models/feed_spec.rb
Closes https://github.com/dreikanter/feeder/issues/428
> Persist feed state update timestamp

- app/controllers/feeds_controller.rb
- app/helpers/sparkline_helper.rb
- app/models/feed.rb
- app/models/sparkline.rb
- app/services/process_feed.rb
- app/services/sparkline_builder.rb
- app/services/sparkline_chart.rb
- app/views/feeds/index.html.erb
- db/migrate/20230616143631_create_sparklines.rb
- db/schema.rb
- spec/models/sparkline_spec.rb
- spec/service/sparkline_builder_spec.rb
- spec/service/sparkline_chart_spec.rb
- test/factories/sparklines.rb
- Generate sparklines for each feed on the index page to show daily import activity.
- Refresh sparklines data after each pull service execution.
> Hello Sparky!

- app/helpers/feeds_table_helper.rb
- app/helpers/sparkline_helper.rb
- app/views/layouts/application.html.erb
> Improve sparklines presentation

- Gemfile
- Gemfile.lock
- config/environments/development.rb
- config/environments/production.rb
- config/environments/staging.rb
- docker-compose.yml
Redis will be used to cache Reddit posts score, instead of the data points model.
> Enable Redis cache store

- config/feeds.yml
It's now possible to explicit feed deactivation.
> Explain deactivation reason to inactive feeds configuration

- app/loaders/kotaku_loader.rb
- app/models/feed.rb
- app/normalizers/feedjira_normalizer.rb
- app/normalizers/kotaku_normalizer.rb
- app/processors/kotaku_processor.rb
- app/services/processor_resolver.rb
- config/feeds.yml
- spec/fixtures/files/feeds/kotaku/normalized.json
- spec/fixtures/files/feeds/kotaku/rss.xml
- spec/loaders/kotaku_loader_spec.rb
- spec/models/feed_spec.rb
- spec/normalizers/kotaku_normalizer_spec.rb
- spec/processors/kotaku_processor_spec.rb
- test/factories/feed_factory.rb
- Extract and persist daily best posts from Kotaku feed.
- Do not publish yet.
> Experimental: Best of Kotaku

- app/normalizers/kotaku_normalizer.rb
- config/feeds.yml
- spec/fixtures/files/feeds/kotaku/normalized.json
- spec/normalizers/kotaku_normalizer_spec.rb
> Enable Kotaku feed

- app/normalizers/kotaku_normalizer.rb
- spec/fixtures/files/feeds/kotaku/normalized.json
> Clean up post summary for Kotaku

- app/normalizers/yesbut_normalizer.rb
> Remove unused class

- app/services/process_feed.rb
- db/migrate/20230630183347_add_state_to_posts.rb
References:
- https://app.honeybadger.io/projects/65419/faults/97338975
> Temporarily remove post state update

- app/models/post.rb
- app/services/freefeed_client_builder.rb
- app/services/push.rb
- spec/models/post_spec.rb
- spec/service/freefeed_client_builder_spec.rb
Reduce feed processing complexity and improve test coverage.
> Move post permalink generation to the model

- app/models/feed_entity.rb
- app/processors/base_processor.rb
- app/processors/hackernews_processor.rb
- spec/models/feed_entity_spec.rb
> Stringify uid during `FeedEntity` initialization

- app/loaders/nitter_loader.rb
- app/models/service_instance.rb
- app/normalizers/kotaku_daily_normalizer.rb
- app/services/nitter_instances_pool_updater.rb
- db/migrate/20230702113522_create_service_instances.rb
- db/schema.rb
- spec/factories/service_instances.rb
- spec/fixtures/files/feeds/kotaku_daily/normalized.json
- spec/loaders/nitter_loader_spec.rb
- spec/models/post_spec.rb
- spec/models/service_instance_spec.rb
- spec/service/nitter_instances_pool_updater_spec.rb
- Introduce generalized service instances model.
- Replace `NitterInstance` model with `ServiceInstance`.
- Replace hardcoded public instances list with the dynamic pool.
> Service instances

- config/feeds.yml
References:
- https://techcrunch.com/2023/07/01/twitter-imposes-limits-on-the-number-of-tweets-users-can-read-amid-extended-outage/
- https://github.com/zedeus/nitter/issues/919
> Disable Twitter feeds

- config/feeds.yml
References:
- #471
- #476
- #383
- #380
- #396
> Enable Nitter feeds

- app/loaders/nitter_loader.rb
- app/models/service_instance.rb
- app/services/reddit_points_fetcher.rb
- spec/loaders/nitter_loader_spec.rb
- spec/models/service_instance_spec.rb
- spec/processors/reddit_processor_spec.rb
- spec/services/reddit_points_fetcher_spec.rb
Updates:
- Enable service instances pool for the `RedditPointsFetcher`.
- Remove default service instance fallback.
- Improve Add more context to Honeybadger.
References:
- #478
- #470
- #383
> Use Libreddit instances pool

- app/support/http_client.rb
https://github.com/dreikanter/feeder/pull/486 follow-up.
> Ensure HTTP feature is loaded

- app/loaders/base_loader.rb
- app/loaders/http_loader.rb
- app/loaders/nitter_loader.rb
- app/models/sparkline.rb
- app/services/downloader.rb
- app/services/libreddit_instance_availability_checker.rb
- app/services/nitter_instance_availability_checker.rb
- app/services/reddit_points_fetcher.rb
- app/support/http_client.rb
- spec/loaders/http_loader_spec.rb
- Use common configuration for HTTP requests timeout and max redirects.
- Remove Callee dependency from loaders.
> Remove repeating code

- app/support/request_tracking.rb
References:
- Multiple fixes didn't work: https://github.com/dreikanter/feeder/issues/491
> For fuck sake Honeybadger

- app/models/service_instance.rb
- app/services/feeds_configuration.rb
- app/services/pull.rb
- app/services/service_instances_pool_updater.rb
- spec/support/shared_examples_a_normalizer.rb
> Prevent redundant content load

- app/services/service_instances_pool_updater.rb
- Fixes delisted instances status update.
- Fixes instances stats for the logging.
> Fix `ServiceInstance` during importing

- app/controllers/service_instances_controller.rb
- app/models/service_instance.rb
- app/services/service_instances_pool_updater.rb
- spec/models/service_instance_spec.rb
> Order service instances by state

- app/loaders/nitter_loader.rb
- app/models/service_instance.rb
- app/services/reddit_points_fetcher.rb
- app/views/service_instances/index.html.erb
- db/migrate/20230804133646_add_usages_count_to_service_instances.rb
- db/schema.rb
- spec/controllers/service_instances_controller_spec.rb
- spec/loaders/nitter_loader_spec.rb
- spec/services/reddit_points_fetcher_spec.rb
- Increment the counter each time a service instance is used.
- Reset counter when service instance is getting enabled.
> Add usages counter for the service instances

- app/models/post.rb
- app/services/feeds_configuration.rb
- app/services/service_instances_pool_updater.rb
- app/services/sparkline_builder.rb
- app/support/logging.rb
- bin/checks
- db/migrate/20230818131852_change_posts_link_default.rb
- db/migrate/20230818131932_add_posts_source_content.rb
- db/schema.rb
- spec/factories/feeds.rb
- spec/fixtures/files/feeds/README.md
- spec/models/feed_spec.rb
- spec/models/post_spec.rb
- Allow blank `Post.link`.
- Add `Post.source_content` attribute.
> Refactoring and preparation for `Pull` update

- app/normalizers/reddit_normalizer.rb
- spec/fixtures/files/feeds/reddit/normalized.json
> Add extra line break to Reddit repost text

- app/services/purge_errors.rb
- config/application.rb
- spec/rails_helper.rb
https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#new-activesupport-cache-serialization-format
> Fix Rails 7.1 deprecation warnings

- app/normalizers/pluralistic_normalizer.rb
- spec/fixtures/files/feeds/pluralistic/normalized.json
Attempt to extract direct URL.
> Fix Pluralistic image attachments

- app/normalizers/elementy_normalizer.rb
- config/feeds.yml
- spec/fixtures/files/feeds/elementy/feed.xml
- spec/fixtures/files/feeds/elementy/normalized.json
- spec/fixtures/files/feeds/elementy/post.html
- spec/normalizers/elementy_normalizer_spec.rb
Closes https://github.com/dreikanter/feeder/issues/551.
> Introduce ElementyNormalizer and add `elementy` feeds

- app/normalizers/melodymae_normalizer.rb
- spec/fixtures/files/feeds/melodymae/normalized.json
- spec/normalizers/melodymae_normalizer_spec.rb
> Check if image is downloadable before attaching

- config/feeds.yml
Closes https://github.com/dreikanter/feeder/issues/561
> Bump refresh intervals for nitter feeds

- app/services/process_feed.rb
- app/services/sparkline_builder.rb
Changes:
- Always rebuild the sparkline after feed update.
- Optimize DB queries during sparkline build.
References:
- Closes https://github.com/dreikanter/feeder/issues/541
> Optimize sparklines builder

- Gemfile.lock
- app/models/feed.rb
- app/services/feed_sanitizer.rb
- config/feeds.yml
- db/migrate/20240728141124_drop_delayed_jobs.rb
- db/migrate/20240817185724_create_error_reports.rb
- db/migrate/20240901154501_rename_feed_attributes.rb
- db/schema.rb
- spec/factories/feeds.rb
- spec/fixtures/files/sample_feeds.yml
- spec/services/feed_sanitizer_spec.rb
- spec/services/feed_updater_spec.rb
- spec/services/feeds_configuration_spec.rb
- Rename feeds.source to source_ulr and add feeds.configured_at
- Drop unused `delayed_jobs` table (merge `f2` schema changes).
- Create `error_reports` table (merge `f2` schema changes).
> INTERNAL: Update feed column names

- Gemfile
- Gemfile.lock
- app/normalizers/base_normalizer.rb
- app/services/importer.rb
- spec/fixtures/files/sample_rss.xml
- spec/normalizers/base_normalizer_spec.rb
- spec/rails_helper.rb
- spec/services/importer_spec.rb
- Finish `Importer` test coverage.
- Add `super_diff` for RSpec logs readability.
- Normalization:
- Prevent multiple validation calls.
- Normalizer will set post state after normalization.
- Skip existing posts during normalization.
> F2: Finish `Importer` test coverage; improve normalization

- README.md
- app/views/layouts/application.html.erb
- app/views/passwords/edit.html.erb
- app/views/passwords/new.html.erb
- app/views/sessions/new.html.erb
- config/environments/production.rb
- Make authentication-related forms look nice.
- Link Bootstrap.
- Update partial views markup.
- Update readme with `puma-dev` setup instructions for local environment.
This should make the prototype UI feel nicer during testing stage:
> F2: Make forms look nice

- app/views/passwords/edit.html.erb
- app/views/passwords/new.html.erb
- lib/freefeed.rb
- lib/freefeed/authenticated_request.rb
- lib/freefeed/client.rb
- lib/freefeed/error.rb
- lib/freefeed/request.rb
- lib/freefeed/utils.rb
- lib/freefeed/v1/attachments.rb
- lib/freefeed/v1/comments.rb
- lib/freefeed/v1/posts.rb
- lib/freefeed/v2/notifications.rb
- lib/freefeed/v2/posts.rb
- lib/freefeed/v2/timelines.rb
- lib/freefeed/v2/users.rb
- spec/lib/freefeed/client_spec.rb
- spec/lib/freefeed/error_spec.rb
- spec/lib/freefeed/request_spec.rb
- spec/lib/freefeed/v1/posts_spec.rb
- spec/lib/freefeed/v2/users_spec.rb
- Merge Freefeed API wrapper.
- Refactor API wrapper.
- Move API wrapper classes to `lib`.
- Ensure `lib` classes are getting autoloaded normally.
- Test coverage.
> F2: Integrate Freefeed API

- app/services/batch_publisher.rb
- app/services/feed_processor.rb
- spec/services/batch_publisher_spec.rb
- spec/services/post_publisher_spec.rb
- Test coverage for the `BatchPublisher`.
- Minor cleaning up and fixes.
> F2: Test `BatchPublisher`
