dreikanter/feeder

- app/loaders/base_loader.rb
- app/processors/base_processor.rb
- test/loaders/base_loader_test.rb
- test/processors/base_processor_test.rb
- test/support/normalizer_test_helper.rb
- test/support/processor_test_helpers.rb
Motivation: `NotImplementedError` is designated to indicate Ruby platform differences, not lacking abstract method implementation.
> Replace NotImplementedError with RuntimeError with a message

- app/controllers/api_controller.rb
- app/services/downloader.rb
Updates:
- Do not wrap errors within `Downloader` class to preserve original error details.
- Add download URL to HB context.
References:
- https://app.honeybadger.io/projects/65419/faults/58605400
> Improve Honeybadger errors notification

- app/loaders/http_loader.rb
- test/loaders/http_loader_test.rb
Use WebMock instead of replacing HTTP client with a mock during testing.
> Remove unnecessary option from HttpLoader

- app/normalizers/twitter_normalizer.rb
- test/feeds/twitter_media_link_test.rb
- test/fixtures/files/feeds/twitter/entity_media_link.json
- test/fixtures/files/feeds/twitter/user_timeline_media_link.json
Relevant for Twitter feeds with image-only tweets. In this case Feed entry text duplicates short media URL, which is redundant.
See #324.
> Prevent Twitter media link duplication in the post body

- app/processors/atom_processor.rb
- app/services/downloader.rb
- spec/service/downloader_spec.rb
Updates:
- Follow redirects.
- Make sure HTTP response is a success, before processing downloaded image.
References:
- #387
> Fix edge cases for the attachment downloader

- config/puma.rb
"Port" option is required in Puma configuration on the production instance.
> Fix port definition for Puma

- app/services/nitter_permalink.rb
- spec/service/nitter_peralink_spec.rb
- spec/service/nitter_permalink_spec.rb
Some Nitter instances return use HTTP permalinks for Tweets. This cause occasional Tweets duplication, since Tweet permalinks are uids.
This patch replaces `http://` with `https://` in addition to replacing Nitter host with `twitter.com`.
> Ensure Twitter permalinks are HTTPS

- app/models/nitter_instance.rb
- spec/models/nitter_instance_spec.rb
Updates:
- Allow registering `NitterInstance` errors in any state to prevent race conditions.
References:
- https://app.honeybadger.io/projects/65419/faults/96754247
> Use more comfortable state transitions for `NitterInstance`

- app/loaders/http_loader.rb
- spec/loaders/http_loader_spec.rb
Medium feed URLs respond with 301.
> Follow HTTP redirects during feed URL load

- config/feeds.yml
Dilbert comics is not in public access any longer.
> Disable Dilbert feed

- app/models/feed.rb
- spec/models/feed_spec.rb
So empty cells won't pop to the top if the feeds list.
> Keep undefined values in the end of the sorted sequence

- Gemfile
- Gemfile.lock
- app/helpers/feeds_table_helper.rb
- app/helpers/formatting_helper.rb
- app/helpers/sparkline_helper.rb
- app/views/feeds/index.html.erb
- app/views/layouts/application.html.erb
- spec/models/feed_spec.rb
- spec/service/feed_updater_spec.rb
- Use compact format for timestamps.
- Turn off word wrapping in the feeds table.
> Improve presentation

- app/models/feed.rb
- app/models/normalized_entity.rb
- app/processors/hackernews_processor.rb
- config/feeds.yml
- spec/fixtures/files/feeds/hackernews/expected_normalizer_result.json
- spec/normalizers/hackernews_normalizer_spec.rb
- spec/processors/hackernews_processor_spec.rb
- test/factories/feed_factory.rb
Why HN duplicates 🤔
```ruby
feed = Feed.find(15)
feed.import_limit = 100
content = feed.loader_class.new(feed).call
entities = feed.processor_class.new(content: content, feed: feed).call
entities.map { _1.content.slice("id", "title")}
Post.where(uid: entities.map { _1.content["id"] }).count
nes = entities.map { feed.normalizer_class.new(_1).call }
existing_uids = Post.where(uid: entities.map { _1.content["id"] }).pluck(:uid)
```
Dupes were caused by the implicit Integer → String conversion.
> Prevent HN duplicates

- app/models/normalized_entity.rb
- app/services/process_feed.rb
- spec/fixtures/files/feeds/commitstrip/entity.json
- spec/fixtures/files/feeds/hackernews/expected_normalizer_result.json
- spec/fixtures/files/feeds/kotaku/normalized.json
- spec/fixtures/files/feeds/kotaku_daily/normalized.json
- spec/fixtures/files/feeds/nextbigfuture/entity.json
- spec/models/normalized_entity_spec.rb
- spec/normalizers/commitstrip_normalizer_spec.rb
- spec/normalizers/hackernews_normalizer_spec.rb
- spec/normalizers/kotaku_daily_normalizer_spec.rb
- spec/normalizers/kotaku_normalizer_spec.rb
- spec/normalizers/nextbigfuture_normalizer_spec.rb
- spec/normalizers/nitter_normalizer_spec.rb
- test/normalizers/infiniteimmortalbens_normalizer_test.rb
- Implement `NormalizedEntity` model as PORO.
- Unify `published_at` timestamp to `DateTime`.
- Do not preprocess timestamp during tests setup.
> Simplify `NormalizedEntity` implementation

- app/support/request_tracking.rb
- spec/support/request_tracking_spec.rb
Ensure breadcrumbs metadata is always a flat Hash to match Honeybadger limitations.
References:
- #491
- https://docs.honeybadger.io/lib/ruby/getting-started/breadcrumbs/#limits
> Fix Honeybadger breadcrumbs for HTTP request

- app/support/request_tracking.rb
- spec/support/request_tracking_spec.rb
Do not use array or Hash values, only scalars.
References:
- #494
- Closes https://github.com/dreikanter/feeder/issues/491
> Fix Honeybadger breadcrumbs metadata

- app/support/request_tracking.rb
- spec/support/request_tracking_spec.rb
`response.status` was a non-primitive object.
References:
- https://github.com/dreikanter/feeder/issues/491
> Stringify Hobeybadger breadcrumbs metadata

- app/support/request_tracking.rb
This reverts commit 7dd054185b792d85c1a9da5e406911f21f45c290.
The bug was caused by broken deployment automation, sorry about that.
> Revert "For fuck sake Honeybadger (#507)"

- app/normalizers/wumo_normalizer.rb
- spec/fixtures/files/feeds/wumo/feed.xml
- spec/fixtures/files/feeds/wumo/normalized.json
- spec/normalizers/tumblr_normalizer_spec.rb
- spec/normalizers/wumo_normalizer_spec.rb
- spec/support/shared_examples_a_normalizer.rb
Changes:
- New `wumo` validation rule.
- Test cov.
- Print actual normalizer result when it doesn't match to simplify expected data update.
> Do not import `wumo` posts with no image

- app/models/normalized_entity.rb
- app/normalizers/base_normalizer.rb
- app/processors/atom_processor.rb
- app/processors/base_processor.rb
- app/processors/feedjira_processor.rb
- app/processors/hackernews_processor.rb
- app/processors/kotaku_daily_processor.rb
- app/processors/lobsters_processor.rb
- app/processors/nitter_processor.rb
- app/processors/reddit_processor.rb
- app/processors/rss_processor.rb
- app/processors/youtube_processor.rb
- app/services/pull.rb
- spec/models/normalized_entity_spec.rb
- spec/normalizers/aerostat_normalizer_spec.rb
- spec/normalizers/base_normalizer_spec.rb
- spec/normalizers/commitstrip_normalizer_spec.rb
- spec/normalizers/hackernews_normalizer_spec.rb
- spec/normalizers/kotaku_daily_normalizer_spec.rb
- spec/normalizers/nextbigfuture_normalizer_spec.rb
- spec/normalizers/nitter_normalizer_spec.rb
- spec/processors/base_processor_spec.rb
- spec/processors/hackernews_processor_spec.rb
- spec/processors/kotaku_daily_processor_spec.rb
- spec/processors/nitter_processor_spec.rb
- spec/processors/reddit_processor_spec.rb
- spec/services/pull_spec.rb
- spec/support/faulty_processor.rb
- spec/support/test_processor.rb
- Make the `BaseNormalizer` validations track stale posts.
- Rename `BaseProcessor#entities` to `#process` (service refactoring preparation).
References:
- #502
> Remove stale posts tracking from `NormalizedEntity`

- app/loaders/nitter_loader.rb
- app/models/service_instance.rb
- app/services/feeds_configuration.rb
- spec/loaders/nitter_loader_spec.rb
References:
- HB: https://app.honeybadger.io/projects/65419/faults/68668020/01H9CWM1DCSME3TPBRTT34MP05#notice-context
> Improve error tracking for missing service instance

- lib/tasks/pull.rake
Using Rake prerequisites to avoid repeating `FeederConfiguration.sync` call before each task.
> Extract configuration to a separate Rake task

- Gemfile.lock
- docker-compose.yml
- spec/rails_helper.rb
- spec/support/factory_bot.rb
- Fix `bundle`/`gem` error that was requiring to run `bundle install` even if you run `bundle install` or any other command.
- Reduce `docker-compose.yml` duplication.
- Finish RSpec setup.
> F2: Fix Ruby environment in the containers

- .reek.yml
- Gemfile
- Gemfile.lock
- app/errors/abstract_method_error.rb
- app/errors/feed_configuration_error.rb
- app/loaders/base_loader.rb
- app/models/error_report.rb
- app/models/feed.rb
- app/models/feed_content.rb
- app/models/feed_entity.rb
- app/normalizers/base_normalizer.rb
- app/processors/base_processor.rb
- app/services/application_logger.rb
- app/services/class_resolver.rb
- app/services/error_reporter.rb
- app/services/feed_importer.rb
- app/services/feed_processor.rb
- app/services/feed_service.rb
- app/services/importer.rb
- app/services/logging.rb
- app/services/post_builder.rb
- app/services/publisher.rb
- app/services/stopwatch.rb
- app/services/text_helpers.rb
- config/application.rb
- db/migrate/20240817185724_create_error_reports.rb
- db/schema.rb
- spec/services/class_resolver_spec.rb
- Rebuild basic services.
- Establish primary feeder workflow.
- Track workflow errors.
> Rebuild primary workflow classes

- app/services/batch_publisher.rb
- app/services/feed_processor.rb
- app/services/post_publisher.rb
- app/services/publisher.rb
- config/feeder.yml
- lib/freefeed/authenticated_request.rb
- lib/freefeed/client.rb
- lib/freefeed/downloader.rb
- lib/freefeed/request.rb
- lib/freefeed/utils.rb
- lib/freefeed/v1/attachments.rb
- lib/freefeed/v2/timelines.rb
- spec/lib/freefeed/authenticated_request_spec.rb
- spec/lib/freefeed/downloader_spec.rb
- spec/lib/freefeed/request_spec.rb
- spec/services/batch_publisher_spec.rb
- spec/services/post_publisher_spec.rb
- Implement Publisher service.
- Refactor Freefeed API wrapper.
- Use consistent terminology in the Freefeed API wrapper.
- Add credentials accessors to the Feeder configuration.
- Move Freefeed-specific `Downloader` service to the API wrapper namespace.
- Use HTTP client as a parameter instead of passing the client params separately.
- Improve terminology.
- Improve test coverage.
> F2: Implement Publisher service
